// Generated by CoffeeScript 1.3.3

module.exports = function(app) {
  app.get('/', function(req, resp) {
    var data;
    data = {
      title: "macrozone.ch"
    };
    return resp.render('index', data);
  });
  app.get('/demo', function(req, resp) {
    var data;
    data = {
      title: "demo"
    };
    return resp.render('demo', data);
  });
  return app.get('/albrik', function(req, resp) {
    var a, data, evens, links;
    links = ["a", "zelle", "B�lle", "schelle"];
    evens = (function() {
      var _i, _results;
      _results = [];
      for (a = _i = 1; _i <= 100; a = ++_i) {
        _results.push(a);
      }
      return _results;
    })();
    console.log(evens);
    data = {
      title: "Albrik",
      links: links
    };
    return resp.render('albrik', data);
  });
};
